## Marcus Nathan J. Calpe | 2-ECED

In [ ]:
 import numpy as np

# Experiment 2

# A. Reproducible Normalization Problem

In [ ]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

mean = X.mean()
std = X.std()

X_normalized = (X - mean) / std
normalized_mean = X_normalized.mean()
normalized_std = X_normalized.std()


print("X:", X_normalized)
print(" ")
print("Mean:", mean)
print(" ")
print("Std:", std)
print(" ")
print("Normalized Mean:", normalized_mean)
print(" ")
print("Normalized std:", normalized_std)

X: [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
 
Mean: 46.36
 
Std: 25.864075471588002
 
Normalized Mean: 0.0
 
Normalized std: 0.9999999999999999


# B. Cubes Divisible by 4 Problem


In [ ]:
C = (np.arange(1,101)**3).reshape(10,10)
div_by_4 = C[C % 4 == 0]
print("Shape of C:", C.shape)
print(" ")
print("Array Divisible by 4:", div_by_4)
print(" ")
print("Number of selected elements:", len(div_by_4))

Shape of C: (10, 10)
 
Array Divisible by 4: [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
 
Number of selected elements: 50


# C. Above-Mean Squares Problem


In [ ]:
S = (np.arange(1,37)**2)
S_mean = S.mean()
above_mean = S[S > mean]

print("S array:", S)
print(" ")
print("S mean:", S_mean)
print(" ")
print("Above mean:", above_mean)
print(" ")
print("Number of selected elements:", len(above_mean))

S array: [   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296]
 
S mean: 450.1666666666667
 
Above mean: [  49   64   81  100  121  144  169  196  225  256  289  324  361  400
  441  484  529  576  625  676  729  784  841  900  961 1024 1089 1156
 1225 1296]
 
Number of selected elements: 30
